version: '3'
services:
 client:
  build:
     context: ./FrontEnd
     dockerfile: Dockerfile
  expose:
     - ${REACT_APP_PORT}
  environment:
     REACT_APP_PORT: ${REACT_APP_PORT}
  ports:
     - ${REACT_APP_PORT}:${REACT_APP_PORT}
  command: npm run start
 