executors:
  node:
    docker:
      - image: circleci/node:8
      - image: circleci/node:11.6-browsers
        environment:
              CHROME_BIN: "/usr/bin/google-chrome"

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - v2-dependencies-{{ checksum "./package.json" }}
        - v2-dependencies-
      paths:
        - ./node_modules
  install_node_modules: &install_node_modules
      run:
        name: Install dependencies
        command: npm install
  save_cache: &save_cache
      save_cache:
        name: Save NPM package cache
        key: v2-dependencies-{{ checksum "./package.json" }}
        paths:
          - ./node_modules

version: 2.1

jobs:
  build:
    executor: node
    working_directory: ~/project/FrontEnd/
    steps:
      - checkout:
          path: ~/project/
      - run:
          name: curr
          command: ls
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build
          command: CI=false npm run build
      - persist_to_workspace:
          root: ~/project/FrontEnd/
          paths:
            - public
  uitest:
    executor: node
    working_directory: ~/project/FrontEnd/
    steps:
      - checkout:
          path: ~/project/
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build
          command: CI=false npm run build
      - run:
          name: curr
          command: npm run mocha
  unittest:
    executor: node
    working_directory: ~/project/FrontEnd/
    steps:
      - checkout:
          path: ~/project/
      # Restore cache at second time
      - run:
          name: Curr Dir
          command: ls
      - <<: *restore_cache
      # Install for first time
      - <<: *install_node_modules
      # Cache the ./node_modules before test.
      - <<: *save_cache
      - run:
          name: Test
          command: npm test
  deploy:
    executor: node
    working_directory: ~/project/FrontEnd/
    steps:
      - checkout:
          path: ~/project/
      - attach_workspace:
          at: ~/project/FrontEnd/
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Build
          command: CI=false npm run build    
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./build -p          
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - unittest
      - build:
          requires:
            - unittest
      - uitest:
          requires:
            - build
      - deploy:
          requires:
            - uitest
          filters:
            branches:
              only: master