// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6c4fe75e-5a5a-4404-8775-383bc12257ad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tZyQqbBiu",
    "aws_user_pools_web_client_id": "2uol5r4ppfeqnolb0qhjv0s978",
    "oauth": {}
};


export default awsmobile;
