// Generated by Selenium IDE
const { Builder, By, Key, until,promise, Capabilities} = require('selenium-webdriver')
const webdriver = require('selenium-webdriver')
const assert = require('assert')
var firefox = require('selenium-webdriver/firefox');
promise.USE_PROMISE_MANAGER = false;
var url = "https://vigilante.netlify.com/login"


describe('Login Module', function() {
  
  let driver
  
  beforeEach(async function() {
    this.timeout(500000)
    var options = new firefox.Options();
    options.addArguments("-headless");
    // options.setBinary("C:/Program Files/Mozilla Firefox/firefox.exe")
    driver = new Builder().forBrowser('firefox').setFirefoxOptions(options).build();
    await driver.get(url);  
  })

  it('Login as Faculty is working', async function() {
    this.timeout(500000)
    await driver.get("https://vigilante.netlify.com/login")
    await driver.manage().window().setRect(1552, 840)
    assert(await driver.findElement(By.css("h1")).getText() == "Log in")
    assert(await driver.findElement(By.css("h3")).getText() == "Digital Course File | Login")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("Faculty2")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Faculty@2000")
    await driver.findElement(By.id("submitbutton")).click()
    await driver.close()
  }).timeout(10000);

  it('Login - Admin', async function() {
    try
    {
    this.timeout(500000)
    await driver.get("https://vigilante.netlify.com/login")
    await driver.manage().window().setRect(1552, 840)
    assert(await driver.findElement(By.css("h1")).getText() == "Log in")
    assert(await driver.findElement(By.css("h3")).getText() == "Digital Course File | Login")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("Admin1")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin@2000")
    await driver.findElement(By.id("submitbutton")).click()

    // driver.wait( until.elementLocated(By.css('var')),  20000).
    //     .then(async function(){});

    // let x=await driver.findElement(By.css("var"));
    // await driver.wait(until.elementIsVisible(x),10000);
    // assert(x.getText() == "ADMIN PAGE")


    await driver.close()
  }
  catch(err)
  {
    console.log("THROWN",err)
  }
  }).timeout(10000);
   
   after(function(){
    this.timeout(3000);
    assert.ok(true)
  });
})
